export const JMC_STUDENT_FAQ = {
  admissionBasis: "For 2026–27, JMC states that undergraduate admissions are based on CUET UG scores conducted by the National Testing Agency.",
  csas: "JMC states that all applicants are expected to register and complete the University of Delhi Common Seat Allocation System, or CSAS, form.",
  minoritySeats: "JMC states that, as a minority women’s institution, 50 percent of undergraduate seats are reserved for Christian Minority Women; the remaining 50 percent are handled directly by the University of Delhi.",
  feePayment: "JMC states that college fees are accepted through its online payment system.",
  feeScope: "JMC publishes first-year annual fees excluding examination fees. The approved JMC facts do not confirm a separate examination-fee amount.",
  scholarships: "JMC states that a number of scholarship opportunities are available, recognising student merit and talent, and that applications may be made at the beginning of the academic year.",
  financialAssistance: "JMC states that students needing financial assistance may apply for fee concession on the prescribed Accounts Office form. Until a concession is sanctioned, fees must be paid; if sanctioned, a refund of eligible payments made at the beginning of the year may subsequently be claimed. JMC also lists support through its Student's Aid Fund and a Book Bank Scheme for needy students.",
  financialAssistanceBoundary: "The approved JMC facts do not confirm an individual student's eligibility, award amount, or the current academic year's application deadline.",
  courseFees: {
    "B.A. (Hons.) Economics": "₹28,680 first-year annual fee excluding examination fee.",
    "B.A. (Hons.) Psychology": "₹29,180 first-year annual fee excluding examination fee.",
    "B.Com. (Hons.)": "₹28,680 first-year annual fee excluding examination fee.",
    "B.Com.": "₹28,680 first-year annual fee excluding examination fee.",
    "B.Sc. (Hons.) Mathematics": "₹28,680 first-year annual fee excluding examination fee.",
    "B.Voc. Healthcare Management": "₹37,070 first-year annual fee excluding examination fee.",
    "B.Voc. Retail Management and IT": "₹37,070 first-year annual fee excluding examination fee.",
    "B.El.Ed.": "₹33,730 first-year annual fee excluding examination fee.",
    "ITEP": "₹51,730 first-year annual fee excluding examination fee.",
  },
  sources: [
    "https://www.jmc.ac.in/admission/ugadmission",
    "https://www.jmc.ac.in/admission/collegefees",
    "https://www.jmc.ac.in/admission/scholarshipsfinancialassistance",
    "https://admission.uod.ac.in/",
  ],
} as const;
